;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	TeX-insert-backslash
	default-indent-new-line
	ignore
	keyboard-escape-quit
	kill-region
	markdown-outdent-or-delete
	org-self-insert-command
	paredit-forward-slurp-sexp
	))

(setq mc/cmds-to-run-once
      '(
	lsp-ui-doc--handle-mouse-movement
	markdown-insert-list-item
	toggle-input-method
	))
