;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	markdown-outdent-or-delete
	org-self-insert-command
	paredit-forward-slurp-sexp
	))

(setq mc/cmds-to-run-once
      '(
	))
