(let
    (
     (gc-cons-threshold most-positive-fixnum)
     (gc-cons-percentage 0.8)
     (file-name-handler-alist nil)
     )
  (require 'benchmark-init)
  (require 'benchmark-init-modes)
  (benchmark-init/activate)
  (add-to-list 'load-path "~/.emacs.d/init/")
  (add-to-list 'load-path "~/.emacs.d/init/lang")
  (add-to-list 'load-path "~/.emacs.d/elpa/emacs-application-framework/"
   )
  (require 'preface)
  (require 'package_archive)
  (require 'misc)
  (require 'rainbow)
  (require 'set_font)
  (require 'set_theme)
  (use-package org_set)
  (require 'lsp_config)
  (require 'company_config)
  (require 'ivy_config)
  (require 'paredit_conf)
  (require 'python-la)
  (require 'racket-la)
  (require 'haskell-la)
  (require 'coq-la)
  (require 'youdic)
  (require 'EAF)
)
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(backup-by-copying t)
 '(backup-directory-alist '(("." . "~/.em_backup")))
 '(delete-old-versions t)
 '(fringe-mode '(10 (\, 2)) nil (fringe))
 '(global-hl-line-mode t)
 '(global-linum-mode t)
 '(kept-new-versions 3)
 '(kept-old-versions 1)
 '(scroll-bar-mode nil)
 '(tool-bar-mode nil)
 '(tooltip-mode nil)
 '(version-control t))
