(let
    (
     (gc-cons-threshold most-positive-fixnum)
     (gc-cons-percentage 0.8)
     (file-name-handler-alist nil)
     )
  (require 'benchmark-init)
  (require 'benchmark-init-modes)
  (benchmark-init/activate)
  (add-to-list 'load-path "~/.emacs.d/init/")
  (add-to-list 'load-path "~/.emacs.d/init/lang")
  (add-to-list 'load-path "~/.emacs.d/elpa/emacs-application-framework/"
	       )
  (require 'preface)
  (require 'package_archive)
  (require 'misc)
  (require 'rainbow)
  (require 'set_theme)
  (require 'set_font)
  (use-package org_set)
  ;(require 'ede_conf)
  (require 'lsp_config)
  (require 'company_config)
  (require 'ivy_config)
  (require 'paredit_conf)
  (require 'python-la)
  (require 'racket-la)
  (require 'haskell-la)
  (require 'c_cpp-la)
  (require 'coq-la)
  (require 'youdic)
  (require 'EAF)
)
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ansi-color-names-vector
   ["#282b33" "#e1c1ee" "#5b94ab" "#cfcf9c" "#819cd6" "#a6c1e0" "#7289bc" "#c6c6c6"])
 '(backup-by-copying t)
 '(backup-directory-alist '(("." . "~/.em_backup")))
 '(delete-old-versions t)
 '(display-line-numbers t)
 '(eaf-find-alternate-file-in-dired t t)
 '(ede-project-directories
   '("/home/loutine/ede_turto/include" "/home/loutine/ede_turto/src" "/home/loutine/ede_turto" "/home/loutine/ede_turtorial/include" "/home/loutine/ede_turtorial/src" "/home/loutine/ede_turtorial" "/home/loutine/a-project-text"))
 '(fci-rule-color "#888395")
 '(jdee-db-active-breakpoint-face-colors (cons "#222228" "#819cd6"))
 '(jdee-db-requested-breakpoint-face-colors (cons "#222228" "#5b94ab"))
 '(jdee-db-spec-breakpoint-face-colors (cons "#222228" "#515462"))
 '(kept-new-versions 3)
 '(kept-old-versions 1)
 '(left-fringe-width 8 t)
 '(objed-cursor-color "#e1c1ee")
 '(package-selected-packages
   '(spaceline cnfonts color-theme-sanityinc-solarized spacemacs-theme avk-emacs-themes apropospriate-theme ccls cmake-mode adoc-mode lsp-ivy projectile quickrun youdao-dictionary use-package sdcv rainbow-mode rainbow-delimiters proof-general posframe ox-twbs org-plus-contrib org-drill org-bullets ob-rust neotree lsp-ui lsp-treemacs highlight-indent-guides goto-chg go-mode doom-themes doom-modeline dashboard dap-mode company-lsp company-coq company-box benchmark-init))
 '(pdf-view-midnight-colors (cons "#c6c6c6" "#282b33"))
 '(rustic-ansi-faces
   ["#282b33" "#e1c1ee" "#5b94ab" "#cfcf9c" "#819cd6" "#a6c1e0" "#7289bc" "#c6c6c6"])
 '(scroll-bar-mode nil)
 '(tool-bar-mode nil)
 '(tooltip-mode nil)
 '(vc-annotate-background "#282b33")
 '(vc-annotate-color-map
   (list
    (cons 20 "#5b94ab")
    (cons 40 "#81a7a6")
    (cons 60 "#a8bba1")
    (cons 80 "#cfcf9c")
    (cons 100 "#c1cab2")
    (cons 120 "#b3c5c9")
    (cons 140 "#a6c1e0")
    (cons 160 "#a6c1e0")
    (cons 180 "#a6c1e0")
    (cons 200 "#a6c1e0")
    (cons 220 "#b9c1e4")
    (cons 240 "#cdc1e9")
    (cons 260 "#e1c1ee")
    (cons 280 "#bda5cb")
    (cons 300 "#998aa8")
    (cons 320 "#756f85")
    (cons 340 "#888395")
    (cons 360 "#888395")))
 '(vc-annotate-very-old-color nil)
 '(version-control t))
