(let
    (
     (gc-cons-threshold most-positive-fixnum)
     (gc-cons-percentage 0.8)
     (file-name-handler-alist nil)
    )
(add-to-list 'load-path "~/.emacs.d/init/")
(require 'package_archive)
(require 'misc)
(require 'preface)
(require 'rainbow)
(require 'set_font)
(require 'set_theme)
(require 'proof_general)
(require 'org_set)
(require 'lsp_config)
(require 'company_config)
(require 'youdic))
