;;; package --- Summary
;;; Commentary:
;;; Code:
(set-face-attribute
 'default nil
 :font (font-spec :name "-pyrs-MonacoB-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1"
		  :weight 'normal
		  :slant 'normal
		  :size 12.0))
(if (display-graphic-p)
    (dolist (charset '(kana han symbol cjk-misc bopomofo))
      (set-fontset-font
       (frame-parameter nil 'font)
       charset
       (font-spec :name "-WQYF-文泉驿等宽微米黑-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1"
		  :weight 'normal
		  :slant 'normal
		  :size 14.0))))

  ;;Auto generated by cnfonts
  ;;<https://github.com/tumashu/cnfonts>

(set-face-attribute 'mode-line nil :font
		    (format   "%s :size=%d"  "MonacoB" 24))
(set-face-attribute 'mode-line-inactive nil :font
		    (format   "%s :size=%d"  "MonacoB" 24))
;; 让 cnfonts 随着 Emacs 自动生效。
;; 让 spacemacs mode-line 中的 Unicode 图标正确显示。
(provide 'set_font)
;;; set_font.el ends here
